### ISSUE TITLE
Lens blur radius - using float instead of int possible?

### ISSUE THREAD

**Issue by Phhofm** [NatLee/Blur-Generator#3]
Hey, thank you for your project, and sorry for making an issue here now

I simply had a question, I would like to use your lens blur on a dataset, basically for sisr (single image super resolution).
The goal is to randomly distribute lens blur over images.
There is two problems for me, one is that lens blur even at radius 3 already feels pretty strong, the second is that it only accepts integers so the whole variance in the dataset is that it chooses for each image either radius 2 or 3 (since 1 does not visually apply lens blur really).

Would it be possible to have lens blur radius input as a float instead (if this even makes sense)?
This way I could control the strength way better, and also the variance of blur in the dataset would be way bigger since i could do a radius=np.random.uniform(1.25,2.75) where it randomly chooses one for each input image so the variance of blur over a 6k images dataset would be way greater than just a 2 or a 3.

Maybe since you might be interested, i had used your lens blur already for the RealWebPhoto upscaling models, for example this one: 
https://github.com/Phhofm/models/releases/tag/4xRealWebPhoto_v2_rgt_s
Where in the pfd in the attachements you can see on page 7 i used this project.

**Comment by NatLee** [comment]
Hi Phhofm,

Thank you for your interest in the lens blur generator and for using it in your project!
I'll make some updates to the code to address your concerns about the blur radius and its intensity. 😎

**Comment by NatLee** [comment]
The question is here.

https://github.com/NatLee/Blur-Generator/blob/c2e69898b281965d6c809d391702370f25f7ac25/src/blurgenerator/lens_blur.py#L60-L65

`kernel_size` must be an Integer of tuple, so we need make parameter `lens_radius` be an 
 `integer`.

**Comment by Phhofm** [comment]
Hey thank you for the quick response and for looking into this :)

Ah, I see. Had hoped it could be used with float to have more strength variance. In general blurs feel pretty strong very fast to me and had hoped this would also be able to decrease strenght by choosing something like 1.75 for example. But yeah if we need to convert into an int again than this would not change much, at least for my use case.

Had also in the meantime played around (saw your changes, checked out the new branch, played around with the code and using your reinstall.sh to then run your cli) by making kernel_size an input in your cli which resulted in more different less strong strengths where kernel 8 would be close to using lens blur radius 3 previously so i could use everything before, 
![kernel1](https://github.com/NatLee/Blur-Generator/assets/14755670/e7dd0915-2b09-4d98-8e88-658ba7101093)
https://slow.pics/c/U90S90iX

but this also resulted in the even images misaligning (like shifting), the odd ones like 3, 5, 7 and 9 did not shift, 3 is pretty much unchanged concerning blur to the original, so taking 5 and 7 would basically result in the same than just using lens radius 2 and 3 as previously since it would be 2 variants of blur.

Anyway thanks for trying :) If it cannot be made weaker then I think then ill just use with with radius 2 and 3 (could also maybe mix in some weak gaussian blur just to increase the variance of blur in the dataset, like the images being blurred with lens or with gaussian instead of only lens).

**Comment by NatLee** [comment]
Hi Phhofm,

Thank you for your feedback and for experimenting with the code.
But I said something wrong in the previous reply because `kernel_size` is just an integer. It's not a tuple.

In the new branch, the `radius` can be used in generating `kernel_complex`

```python
ax = np.linspace(-radius, radius, kernel_size, dtype=np.float32)
ax = ax * scale * (1 / radius)
```

I think we handle the floating-point radius will make the filter look more smoothly.

About the misalignment issue, `kernel_size = kernel_radius * 2 + 1` is used to determine the size of the kernel (filter) used for convolution in image processing.
The `kernel_radius` represents half the width of the kernel, not including the center element.
For example, if the `kernel_radius` is 3, it means that the kernel extends 3 pixels to the left and 3 pixels to the right of the center pixel.

It may like this:

```
| -3 | -2 | -1 | 0 | 1 | 2 | 3 |
```

The size of the kernel (kernel_size) needs to encompass all the pixels within the kernel_radius plus the center pixel.
Therefore, if the kernel_radius is 3, the total width of the kernel is 3 (left) + 1 (center) + 3 (right) = 7.

That is, the kernel size must be `an odd number` to have a single center pixel, which is essential for symmetrical processing around the center pixel. 😎

----

As we mention the filter, I notice another problem. 😄
In the code, we processed the filter with default `boarderType`. ([See details](https://docs.opencv.org/4.x/d2/de8/group__core__array.html#ga209f2f4869e304c82d07739337eae7c5))

https://github.com/NatLee/Blur-Generator/blob/c2e69898b281965d6c809d391702370f25f7ac25/src/blurgenerator/lens_blur.py#L109-L117

Maybe we can adjust it to `cv2.BORDER_REPLICATE` to ensure proper handling of filters border. 🤔

**Comment by NatLee** [comment]
@Phhofm I temperarily close this issue.
It'll support floating-point for lens radius in next version. :)

Thank you for using this package in your project.
If you have other questions, any time here 👍
